// words/word-c.js
if (!window.builtInThemes) {
    window.builtInThemes = {};
}

window.builtInThemes.cap_c = [
    { word: "cabbage", phonetic: "/ˈkæb.ɪdʒ/", meaning: "n. 高麗菜 / 包心菜", example: "My mother bought a fresh cabbage at the market." },
    { word: "cable", phonetic: "/ˈkeɪ.bəl/", meaning: "n. 電纜 / 纜線", example: "Plug the cable into the computer." },
    { word: "cafeteria", phonetic: "/ˌkæf.əˈtɪə.ri.ə/", meaning: "n. 自助餐廳 / 食堂", example: "We usually have lunch in the school cafeteria." },
    { word: "cage", phonetic: "/keɪdʒ/", meaning: "n. 鳥籠 / 籠子", example: "The bird opened the cage and flew away." },
    { word: "cake", phonetic: "/keɪk/", meaning: "n. 蛋糕", example: "We ate chocolate cake on my birthday." },
    { word: "calendar", phonetic: "/ˈkæl.ən.dər/", meaning: "n. 日曆 / 月曆", example: "Check the calendar for the exam date." },
    { word: "call", phonetic: "/kɔːl/", meaning: "v. 打電話 / 呼喚", example: "I will call you when I arrive home." },
    { word: "calm", phonetic: "/kɑːm/", meaning: "adj. 平靜的 / 沉著的", example: "Keep calm and stay focused during the test." },
    { word: "camera", phonetic: "/ˈkæm.rə/", meaning: "n. 照相機", example: "He took pictures of the beach with his camera." },
    { word: "camp", phonetic: "/kæmp/", meaning: "v. 露營 / n. 營地", example: "We decided to camp by the lake this weekend." },
    { word: "campaign", phonetic: "/kæmˈpeɪn/", meaning: "n. 活動 / 運動", example: "The school started a clean energy campaign." },
    { word: "can", phonetic: "/kæn/", meaning: "aux. 能夠 / n. 罐頭", example: "She can play the piano very well." },
    { word: "cancel", phonetic: "/ˈkæn.səl/", meaning: "v. 取消", example: "They had to cancel the flight due to bad weather." },
    { word: "cancer", phonetic: "/ˈkæn.sər/", meaning: "n. 癌症", example: "Eating healthy food helps prevent cancer." },
    { word: "candle", phonetic: "/ˈkæn.dəl/", meaning: "n. 蠟燭", example: "She blew out the candles on her birthday cake." },
    { word: "candy", phonetic: "/ˈkæn.di/", meaning: "n. 糖果", example: "Eating too much candy is bad for your teeth." },
    { word: "cap", phonetic: "/kæp/", meaning: "n. 帽子 / 瓶蓋", example: "He wears a baseball cap to keep the sun off." },
    { word: "capable", phonetic: "/ˈkeɪ.pə.bəl/", meaning: "adj. 有能力的", example: "She is capable of handling difficult tasks." },
    { word: "captain", phonetic: "/ˈkæp.tɪn/", meaning: "n. 船長 / 隊長", example: "The basketball captain led his team to victory." },
    { word: "car", phonetic: "/kɑːr/", meaning: "n. 汽車", example: "My father drives a blue car to work." },
    { word: "card", phonetic: "/kɑːd/", meaning: "n. 卡片", example: "I sent a Christmas card to my friend." },
    { word: "care", phonetic: "/keər/", meaning: "v. 關心 / 在意 / n. 照顧", example: "Parents care deeply about their children." },
    { word: "career", phonetic: "/kəˈrɪər/", meaning: "n. 職業 / 生涯", example: "She wants to build a career in music." },
    { word: "careful", phonetic: "/ˈkeə.fəl/", meaning: "adj. 小心的", example: "Be careful when crossing the busy street." },
    { word: "careless", phonetic: "/ˈkeə.ləs/", meaning: "adj. 粗心的", example: "He made a careless mistake on the test." },
    { word: "carpet", phonetic: "/ˈkɑː.pɪt/", meaning: "n. 地毯", example: "The living room floor is covered with a soft carpet." },
    { word: "carrot", phonetic: "/ˈkær.ət/", meaning: "n. 胡蘿蔔", example: "Rabbits love to eat fresh carrots." },
    { word: "carry", phonetic: "/ˈkær.i/", meaning: "v. 提 / 拿 / 攜帶", example: "Can you help me carry these heavy boxes?" },
    { word: "cart", phonetic: "/kɑːt/", meaning: "n. 手推車", example: "Fill the shopping cart with groceries." },
    { word: "cartoon", phonetic: "/kɑːˈtuːn/", meaning: "n. 卡通", example: "Children like watching cartoons on Saturday mornings." },
    { word: "case", phonetic: "/keɪs/", meaning: "n. 情況 / 案件 / 盒子", example: "In that case, we should leave early." },
    { word: "cash", phonetic: "/kæʃ/", meaning: "n. 現金", example: "Do you want to pay in cash or by credit card?" },
    { word: "castle", phonetic: "/ˈkɑː.səl/", meaning: "n. 城堡", example: "They visited an ancient castle during the trip." },
    { word: "cat", phonetic: "/kæt/", meaning: "n. 貓", example: "The cute cat is sleeping on the sofa." },
    { word: "catch", phonetic: "/kætʃ/", meaning: "v. 抓住 / 接住 / 趕上", example: "Hurry up or we won't catch the bus." },
    { word: "cause", phonetic: "/kɔːz/", meaning: "v. 導致 / n. 原因", example: "Heavy rain caused severe flooding in the city." },
    { word: "ceiling", phonetic: "/ˈsiː.lɪŋ/", meaning: "n. 天花板", example: "A beautiful lamp hangs from the ceiling." },
    { word: "celebrate", phonetic: "/ˈsel.ə.breɪt/", meaning: "v. 慶祝", example: "We gathered together to celebrate New Year's Eve." },
    { word: "cell", phonetic: "/sel/", meaning: "n. 細胞 / 單元格", example: "All living organisms are made of cells." },
    { word: "cellphone", phonetic: "/ˈsel.fəʊn/", meaning: "n. 手機", example: "Don't look at your cellphone while driving." },
    { word: "cent", phonetic: "/sent/", meaning: "n. 分（貨幣單位）", example: "This candy costs fifty cents." },
    { word: "center", phonetic: "/ˈsen.tər/", meaning: "n. 中心 / 中堅", example: "The shopping center is crowded on weekends." },
    { word: "central", phonetic: "/ˈsen.trəl/", meaning: "adj. 中央的 / 主要的", example: "They live near Central Park." },
    { word: "century", phonetic: "/ˈsen.tʃər.i/", meaning: "n. 世紀 / 一百年", example: "The building was constructed in the nineteenth century." },
    { word: "cereal", phonetic: "/ˈsɪə.ri.əl/", meaning: "n. 麥片 / 穀類食物", example: "I eat a bowl of cereal with milk every morning." },
    { word: "certain", phonetic: "/ˈsɜː.tən/", meaning: "adj. 確定的 / 某種", example: "I am certain that she will win the game." },
    { word: "certainly", phonetic: "/ˈsɜː.tən.li/", meaning: "adv. 當然 / 必定", example: "I will certainly finish the work on time." },
    { word: "chain", phonetic: "/tʃeɪn/", meaning: "n. 鏈條 / 連鎖店", example: "He bought coffee from a famous chain store." },
    { word: "chair", phonetic: "/tʃeər/", meaning: "n. 椅子", example: "Please take a chair and sit down." },
    { word: "chalk", phonetic: "/tʃɔːk/", meaning: "n. 粉筆", example: "The teacher wrote on the board with white chalk." },
    { word: "challenge", phonetic: "/ˈtʃæl.ɪndʒ/", meaning: "n. 挑戰 / v. 挑戰", example: "Learning a new language is a fun challenge." },
    { word: "chance", phonetic: "/tʃɑːns/", meaning: "n. 機會 / 可能性", example: "Don't miss this great chance to study abroad." },
    { word: "change", phonetic: "/tʃeɪndʒ/", meaning: "v. 改變 / n. 零錢", example: "Weather can change quickly in the mountains." },
    { word: "channel", phonetic: "/ˈtʃæn.əl/", meaning: "n. 頻道 / 水道", example: "Switch to channel five to watch the news." },
    { word: "character", phonetic: "/ˈkær.ək.tər/", meaning: "n. 性格 / 角色 / 文字", example: "He is a movie character that kids love." },
    { word: "charge", phonetic: "/tʃɑːdʒ/", meaning: "v. 充電 / 收費 / n. 費用", example: "I need to charge my phone battery." },
    { word: "chart", phonetic: "/tʃɑːt/", meaning: "n. 圖表", example: "Look at the chart to see the sales results." },
    { word: "chase", phonetic: "/tʃeɪs/", meaning: "v. 追逐 / 驅趕", example: "The cat likes to chase mice." },
    { word: "cheap", phonetic: "/tʃiːp/", meaning: "adj. 便宜的", example: "This T-shirt is very cheap and comfortable." },
    { word: "cheat", phonetic: "/tʃiːt/", meaning: "v. 作弊 / 欺騙", example: "It is wrong to cheat on exams." },
    { word: "check", phonetic: "/tʃek/", meaning: "v. 檢查 / n. 支票", example: "Check your answers before handing in the paper." },
    { word: "cheer", phonetic: "/tʃɪər/", meaning: "v. 歡呼 / 鼓舞", example: "The crowd cheered loudly for the players." },
    { word: "cheerful", phonetic: "/ˈtʃɪə.fəl/", meaning: "adj. 快樂的 / 愉快的", example: "She always greets everyone with a cheerful smile." },
    { word: "cheese", phonetic: "/tʃiːz/", meaning: "n. 起司 / 乾酪", example: "I like pizza with extra cheese." },
    { word: "chemistry", phonetic: "/ˈkem.ɪ.stri/", meaning: "n. 化學", example: "We do experiments in chemistry class." },
    { word: "chess", phonetic: "/tʃes/", meaning: "n. 西洋棋", example: "My grandfather taught me how to play chess." },
    { word: "chicken", phonetic: "/ˈtʃɪk.ɪn/", meaning: "n. 雞 / 雞肉", example: "We had fried chicken for dinner." },
    { word: "chief", phonetic: "/tʃiːf/", meaning: "adj. 主要的 / n. 首領", example: "He is the chief editor of the magazine." },
    { word: "child", phonetic: "/tʃaɪld/", meaning: "n. 小孩", example: "Every child deserves a happy childhood." },
    { word: "childhood", phonetic: "/ˈtʃaɪld.hʊd/", meaning: "n. 童年", example: "I spent my childhood in a peaceful country village." },
    { word: "children", phonetic: "/ˈtʃɪl.drən/", meaning: "n. 小孩們（複數）", example: "The children are playing happily in the park." },
    { word: "chin", phonetic: "/tʃɪn/", meaning: "n. 下巴", example: "He rested his chin on his hand and listened." },
    { word: "china", phonetic: "/ˈtʃaɪ.nə/", meaning: "n. 中國", example: "China is located in East Asia." },
    { word: "chinese", phonetic: "/tʃaɪˈniːz/", meaning: "adj. 中國的 / n. 中文", example: "She is learning Chinese grammar." },
    { word: "chocolate", phonetic: "/ˈtʃɒk.lət/", meaning: "n. 巧克力", example: "Hot chocolate tastes great in winter." },
    { word: "choice", phonetic: "/tʃɔɪs/", meaning: "n. 選擇", example: "You have a choice between coffee and tea." },
    { word: "choose", phonetic: "/tʃuːz/", meaning: "v. 選擇", example: "Choose the correct answer for each question." },
    { word: "chopsticks", phonetic: "/ˈtʃɒp.stɪks/", meaning: "n. 筷子", example: "In Taiwan, people use chopsticks to eat noodles." },
    { word: "christmas", phonetic: "/ˈkrɪs.məs/", meaning: "n. 聖誕節", example: "We exchange gifts on Christmas Day." },
    { word: "church", phonetic: "/tʃɜːtʃ/", meaning: "n. 教會 / 教堂", example: "They go to church every Sunday morning." },
    { word: "circle", phonetic: "/ˈsɜː.kəl/", meaning: "n. 圓圈 / v. 畫圈", example: "Draw a circle around the correct word." },
    { word: "city", phonetic: "/ˈsɪt.i/", meaning: "n. 城市", example: "Taipei is a very modern city." },
    { word: "claim", phonetic: "/kleɪm/", meaning: "v. 宣稱 / 主張", example: "He claimed that he didn't break the glass." },
    { word: "clap", phonetic: "/klæp/", meaning: "v. 拍手 / 鼓掌", example: "Everyone clapped after the amazing show." },
    { word: "class", phonetic: "/klɑːs/", meaning: "n. 班級 / 課堂", example: "Our English class starts at nine o'clock." },
    { word: "classic", phonetic: "/ˈklæs.ɪk/", meaning: "adj. 經典的", example: "This book is a classic example of literature." },
    { word: "classmate", phonetic: "/ˈklɑːs.meɪt/", meaning: "n. 同班同學", example: "She is my favorite classmate in junior high." },
    { word: "classroom", phonetic: "/ˈklɑːs.ruːm/", meaning: "n. 教室", example: "Please keep the classroom clean." },
    { word: "clean", phonetic: "/kliːn/", meaning: "adj. 乾淨的 / v. 打掃", example: "Remember to clean your room today." },
    { word: "clear", phonetic: "/klɪər/", meaning: "adj. 晴朗的 / 清楚的", example: "The sky is blue and clear today." },
    { word: "clearly", phonetic: "/ˈklɪə.li/", meaning: "adv. 清楚地", example: "Please speak clearly so everyone can hear." },
    { word: "clerk", phonetic: "/klɑːk/", meaning: "n. 店員 / 文員", example: "The store clerk helped me find the shoes." },
    { word: "clever", phonetic: "/ˈklev.ər/", meaning: "adj. 聰明的", example: "That clever dog can open the door." },
    { word: "climate", phonetic: "/ˈklaɪ.mət/", meaning: "n. 氣候", example: "Taiwan has a warm and humid climate." },
    { word: "climb", phonetic: "/klaɪm/", meaning: "v. 攀登 / 爬", example: "They plan to climb the mountain this weekend." },
    { word: "clock", phonetic: "/klɒk/", meaning: "n. 時鐘", example: "Look at the clock on the wall." },
    { word: "close", phonetic: "/kləʊz/", meaning: "v. 關閉 / adj. 親密的", example: "Close the door when you leave." },
    { word: "closet", phonetic: "/ˈklɒz.ɪt/", meaning: "n. 壁櫥 / 衣櫃", example: "Hang your coat in the closet." },
    { word: "cloth", phonetic: "/klɒθ/", meaning: "n. 布料", example: "Wipe the table with a wet cloth." },
    { word: "clothes", phonetic: "/kləʊðz/", meaning: "n. 衣服", example: "She bought some new clothes for school." },
    { word: "clothing", phonetic: "/ˈkləʊ.ðɪŋ/", meaning: "n. 衣物", example: "Wear warm clothing in cold weather." },
    { word: "cloud", phonetic: "/klaʊd/", meaning: "n. 雲", example: "White clouds are floating in the sky." },
    { word: "cloudy", phonetic: "/ˈklaʊ.di/", meaning: "adj. 多雲的", example: "It is cloudy today, so it might rain." },
    { word: "club", phonetic: "/klʌb/", meaning: "n. 社團 / 俱樂部", example: "I joined the music club this semester." },
    { word: "coach", phonetic: "/kəʊtʃ/", meaning: "n. 教練", example: "The basketball coach taught us new skills." },
    { word: "coal", phonetic: "/kəʊl/", meaning: "n. 煤炭", example: "Coal was used to power steam engines." },
    { word: "coast", phonetic: "/kəʊst/", meaning: "n. 海岸", example: "They drove along the east coast of Taiwan." },
    { word: "coat", phonetic: "/kəʊt/", meaning: "n. 大衣 / 外套", example: "Put on your warm coat before going out." },
    { word: "cockroach", phonetic: "/ˈkɒk.rəʊtʃ/", meaning: "n. 蟑螂", example: "She screamed when she saw a cockroach." },
    { word: "coffee", phonetic: "/ˈkɒf.i/", meaning: "n. 咖啡", example: "My father drinks a cup of black coffee every morning." },
    { word: "coin", phonetic: "/kɔɪn/", meaning: "n. 硬幣", example: "He put a coin into the vending machine." },
    { word: "coke", phonetic: "/kəʊk/", meaning: "n. 可樂", example: "I ordered a hamburger and a Coke." },
    { word: "cold", phonetic: "/kəʊld/", meaning: "adj. 寒利的 / n. 感冒", example: "Drink hot water when you catch a cold." },
    { word: "collect", phonetic: "/kəˈlekt/", meaning: "v. 收集", example: "He likes to collect foreign stamps." },
    { word: "collection", phonetic: "/kəˈlek.ʃən/", meaning: "n. 收藏品 / 收集", example: "She has a large collection of art books." },
    { word: "college", phonetic: "/ˈkɒl.ɪdʒ/", meaning: "n. 大學 / 學院", example: "My brother will enter college next autumn." },
    { word: "color", phonetic: "/ˈkʌl.ər/", meaning: "n. 顏色 / v. 上色", example: "What is your favorite color?" },
    { word: "colorful", phonetic: "/ˈkʌl.ə.fəl/", meaning: "adj. 多彩的", example: "The garden is full of colorful flowers." },
    { word: "comb", phonetic: "/kəʊm/", meaning: "n. 梳子 / v. 梳頭", example: "Comb your hair before going out." },
    { word: "come", phonetic: "/kʌm/", meaning: "v. 來 / 到達", example: "Come here and look at this picture." },
    { word: "comfortable", phonetic: "/ˈkʌm.fə.tə.bəl/", meaning: "adj. 舒服的", example: "This sofa is very comfortable to sit on." },
    { word: "comic", phonetic: "/ˈkɒm.ɪk/", meaning: "adj. 搞笑的 / n. 漫畫", example: "He loves reading comic books after school." },
    { word: "command", phonetic: "/kəˈmɑːnd/", meaning: "v. 指揮 / 命令", example: "The officer commanded his men to stop." },
    { word: "comment", phonetic: "/ˈkɒm.ent/", meaning: "n. 評論 / v. 發表意見", example: "She left a positive comment on the post." },
    { word: "common", phonetic: "/ˈkɒm.ən/", meaning: "adj. 常見的 / 共同的", example: "Flu is a common illness in winter." },
    { word: "company", phonetic: "/ˈkʌm.pə.ni/", meaning: "n. 公司 / 陪伴", example: "His father works in a technology company." },
    { word: "compare", phonetic: "/kəmˈpeər/", meaning: "v. 比較", example: "Don't compare yourself with others." },
    { word: "complain", phonetic: "/kəmˈpleɪn/", meaning: "v. 抱怨", example: "He complained about the noisy neighbors." },
    { word: "complete", phonetic: "/kəmˈpliːt/", meaning: "v. 完成 / adj. 完整的", example: "Please complete the task by Friday." },
    { word: "complex", phonetic: "/ˈkɒm.pleks/", meaning: "adj. 複雜的", example: "The math problem is too complex for me." },
    { word: "computer", phonetic: "/kəmˈpjuː.tər/", meaning: "n. 電腦", example: "She uses her computer to write reports." },
    { word: "concern", phonetic: "/kənˈsɜːn/", meaning: "n. 關心 / 憂慮", example: "Health is a major concern for elderly people." },
    { word: "concert", phonetic: "/ˈkɒn.sət/", meaning: "n. 音樂會 / 演唱會", example: "We bought tickets for the pop concert." },
    { word: "conclude", phonetic: "/kənˈkluːd/", meaning: "v. 結論 / 結束", example: "He concluded his speech with a thank you." },
    { word: "condition", phonetic: "/kənˈdɪʃ.ən/", meaning: "n. 狀況 / 條件", example: "The car is still in good condition." },
    { word: "confirm", phonetic: "/kənˈfɜːm/", meaning: "v. 確認", example: "Please call to confirm your reservation." },
    { word: "congratulate", phonetic: "/kənˈɡrætʃ.ə.leɪt/", meaning: "v. 祝賀", example: "We congratulate you on passing the exam!" },
    { word: "connect", phonetic: "/kəˈnekt/", meaning: "v. 連接", example: "Connect the laptop to the Wi-Fi network." },
    { word: "consider", phonetic: "/kənˈsɪd.ər/", meaning: "v. 考慮", example: "You should consider taking a short break." },
    { word: "considerate", phonetic: "/kənˈsɪd.ər.ət/", meaning: "adj. 體貼的", example: "It was very considerate of you to help." },
    { word: "contact", phonetic: "/ˈkɒn.tækt/", meaning: "v. 聯絡 / n. 接觸", example: "Feel free to contact me if you have questions." },
    { word: "contain", phonetic: "/kənˈteɪn/", meaning: "v. 包含", example: "This drink contains a lot of sugar." },
    { word: "continue", phonetic: "/kənˈtɪn.juː/", meaning: "v. 繼續", example: "The rain will continue until tomorrow." },
    { word: "contract", phonetic: "/ˈkɒn.trækt/", meaning: "n. 合同 / 契約", example: "Read the contract carefully before signing." },
    { word: "control", phonetic: "/kənˈtrəʊl/", meaning: "v. 控制 / n. 控制", example: "Try to control your anger when upset." },
    { word: "convenient", phonetic: "/kənˈviː.ni.ənt/", meaning: "adj. 方便的", example: "Living near a subway station is very convenient." },
    { word: "conversation", phonetic: "/ˌkɒn.vəˈseɪ.ʃən/", meaning: "n. 對話", example: "They had a long conversation about school." },
    { word: "cook", phonetic: "/kʊk/", meaning: "v. 煮飯 / n. 廚師", example: "My dad loves to cook dinner for us." },
    { word: "cookie", phonetic: "/ˈkʊk.i/", meaning: "n. 餅乾", example: "She baked delicious chocolate cookies." },
    { word: "cool", phonetic: "/kuːl/", meaning: "adj. 涼爽的 / 酷的", example: "The autumn breeze feels nice and cool." },
    { word: "copy", phonetic: "/ˈkɒp.i/", meaning: "v. 複製 / 抄寫 / n. 副本", example: "Copy the vocabulary into your notebook." },
    { word: "corn", phonetic: "/kɔːn/", meaning: "n. 玉米", example: "Grilled corn is a popular night market food." },
    { word: "corner", phonetic: "/ˈkɔː.nər/", meaning: "n. 角落 / 街角", example: "The bakery is at the corner of the street." },
    { word: "correct", phonetic: "/kəˈrekt/", meaning: "adj. 正確的 / v. 訂正", example: "Make sure your answer is correct." },
    { word: "cost", phonetic: "/kɒst/", meaning: "v. 花費 / n. 費用", example: "How much does this book cost?" },
    { word: "cotton", phonetic: "/ˈkɒt.ən/", meaning: "n. 棉花", example: "This shirt is made of pure cotton." },
    { word: "couch", phonetic: "/kaʊtʃ/", meaning: "n. 長沙發", example: "He fell asleep on the couch while watching TV." },
    { word: "cough", phonetic: "/kɒf/", meaning: "v. 咳嗽 / n. 咳嗽", example: "He has a bad cough and needs to rest." },
    { word: "count", phonetic: "/kaʊnt/", meaning: "v. 數數 / 計算", example: "Can you count from one to one hundred?" },
    { word: "country", phonetic: "/ˈkʌn.tri/", meaning: "n. 國家 / 鄉村", example: "Taiwan is a beautiful country." },
    { word: "countryside", phonetic: "/ˈkʌn.tri.saɪd/", meaning: "n. 郊外 / 鄉村地區", example: "They enjoy the fresh air in the countryside." },
    { word: "couple", phonetic: "/ˈkʌp.əl/", meaning: "n. 一對 / 夫妻", example: "The young couple walked hand in hand." },
    { word: "courage", phonetic: "/ˈkʌr.ɪdʒ/", meaning: "n. 勇氣", example: "Have the courage to stand up for yourself." },
    { word: "course", phonetic: "/kɔːs/", meaning: "n. 課程 / 過程", example: "She is taking an online English course." },
    { word: "court", phonetic: "/kɔːt/", meaning: "n. 球場 / 法庭", example: "Let's meet at the basketball court." },
    { word: "cousin", phonetic: "/ˈkʌz.ən/", meaning: "n. 堂/表兄弟姊妹", example: "My cousin lives in Kaohsiung." },
    { word: "cover", phonetic: "/ˈkʌv.ər/", meaning: "v. 覆蓋 / 遮蓋 / n. 封面", example: "Snow covered the mountain top." },
    { word: "cow", phonetic: "/kaʊ/", meaning: "n. 母牛 / 奶牛", example: "The farmer milks the cow every morning." },
    { word: "cowboy", phonetic: "/ˈkaʊ.bɔɪ/", meaning: "n. 牛仔", example: "The cowboy rode his horse across the desert." },
    { word: "crab", phonetic: "/kræb/", meaning: "n. 螃蟹", example: "We caught a small crab at the beach." },
    { word: "crayon", phonetic: "/ˈkreɪ.ɒn/", meaning: "n. 蠟筆", example: "The child is drawing a picture with crayons." },
    { word: "crazy", phonetic: "/ˈkreɪ.zi/", meaning: "adj. 瘋狂的", example: "He is crazy about playing video games." },
    { word: "create", phonetic: "/kriˈeɪt/", meaning: "v. 創造", example: "Artists create beautiful paintings." },
    { word: "credit", phonetic: "/ˈkred.ɪt/", meaning: "n. 信用 / 信譽", example: "She paid for the clothes with a credit card." },
    { word: "crime", phonetic: "/kraɪm/", meaning: "n. 犯罪 / 罪行", example: "Stealing is a serious crime." },
    { word: "cross", phonetic: "/krɒs/", meaning: "v. 穿越 / n. 十字架", example: "Cross the road carefully." },
    { word: "crowd", phonetic: "/kraʊd/", meaning: "n. 人群", example: "A large crowd gathered to watch the game." },
    { word: "crowded", phonetic: "/ˈkraʊ.dɪd/", meaning: "adj. 擁擠的", example: "The night market is very crowded tonight." },
    { word: "cruel", phonetic: "/krʊəl/", meaning: "adj. 殘忍的", example: "It is cruel to treat animals badly." },
    { word: "cry", phonetic: "/kraɪ/", meaning: "v. 哭泣 / 喊叫", example: "Don't cry, everything will be fine." },
    { word: "culture", phonetic: "/ˈkʌl.tʃər/", meaning: "n. 文化", example: "I like learning about foreign cultures." },
    { word: "cup", phonetic: "/kʌp/", meaning: "n. 杯子", example: "Would you like a cup of tea?" },
    { word: "cure", phonetic: "/kjʊər/", meaning: "v. 治癒 / n. 治療方法", example: "Doctors hope to find a cure for cancer." },
    { word: "curious", phonetic: "/ˈkjʊə.ri.əs/", meaning: "adj. 好奇的", example: "Children are always curious about new things." },
    { word: "curtain", phonetic: "/ˈkɜː.tən/", meaning: "n. 窗簾", example: "Open the curtain to let light in." },
    { word: "curve", phonetic: "/kɜːv/", meaning: "n. 轉彎 / 曲線", example: "Drive slowly around the sharp curve." },
    { word: "custom", phonetic: "/ˈkʌs.təm/", meaning: "n. 風俗 / 習俗", example: "Eating mooncakes is a Mid-Autumn custom." },
    { word: "customer", phonetic: "/ˈkʌs.tə.mər/", meaning: "n. 顧客", example: "The shop clerk served the customer politely." },
    { word: "cut", phonetic: "/kʌt/", meaning: "v. 切 / 剪", example: "Cut the cake into six pieces." },
    { word: "cute", phonetic: "/kjuːt/", meaning: "adj. 可愛的", example: "Look at that cute little puppy!" }
];
