// words/word-a.js
if (!window.builtInThemes) {
    window.builtInThemes = {};
}

window.builtInThemes.cap_a = [
    { word: "ability", phonetic: "/əˈbɪl.ə.ti/", meaning: "n. 能力", example: "She has the ability to pass the exam easily." },
    { word: "able", phonetic: "/ˈeɪ.bəl/", meaning: "adj. 能夠的", example: "He is able to speak three languages." },
    { word: "about", phonetic: "/əˈbaʊt/", meaning: "prep. 關於", example: "We are talking about our summer plans." },
    { word: "above", phonetic: "/əˈbʌv/", meaning: "prep. 在…上方", example: "The plane flew above the clouds." },
    { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "adv. 在國外", example: "My sister plans to study abroad next year." },
    { word: "absent", phonetic: "/ˈæb.sənt/", meaning: "adj. 缺席的", example: "Why were you absent from school yesterday?" },
    { word: "accept", phonetic: "/əkˈsept/", meaning: "v. 接受", example: "She decided to accept the job offer." },
    { word: "accident", phonetic: "/ˈæk.sə.dənt/", meaning: "n. 意外", example: "Drive carefully to avoid an accident." },
    { word: "across", phonetic: "/əˈkrɒs/", meaning: "prep. 穿過", example: "Walk across the street carefully." },
    { word: "act", phonetic: "/ækt/", meaning: "v. 行動 / 表演", example: "Think carefully before you act." },
    { word: "action", phonetic: "/ˈæk.ʃən/", meaning: "n. 行動", example: "Actions speak louder than words." },
    { word: "active", phonetic: "/ˈæk.tɪv/", meaning: "adj. 活躍的", example: "He plays an active role in the team." },
    { word: "activity", phonetic: "/ækˈtɪv.ə.ti/", meaning: "n. 活動", example: "Swimming is my favorite outdoor activity." },
    { word: "actor", phonetic: "/ˈæk.tər/", meaning: "n. 男演員", example: "He wants to become a famous actor." },
    { word: "actress", phonetic: "/ˈæk.trəs/", meaning: "n. 女演員", example: "The actress played her role very well." },
    { word: "add", phonetic: "/æd/", meaning: "v. 增加", example: "Add some salt to the soup." },
    { word: "address", phonetic: "/əˈdres/", meaning: "n. 地址", example: "Please write down your email address." },
    { word: "admire", phonetic: "/ədˈmaɪər/", meaning: "v. 欽佩", example: "I admire her for her hard work." },
    { word: "advice", phonetic: "/ədˈvaɪs/", meaning: "n. 建議", example: "My teacher gave me some good advice." },
    { word: "advise", phonetic: "/ədˈvaɪz/", meaning: "v. 建議", example: "The doctor advised me to rest more." },
    { word: "afraid", phonetic: "/əˈfreɪd/", meaning: "adj. 害怕的", example: "Don't be afraid of making mistakes." },
    { word: "after", phonetic: "/ˈɑːf.tər/", meaning: "prep. 在…之後", example: "We can play basketball after school." },
    { word: "afternoon", phonetic: "/ˌɑːf.təˈnuːn/", meaning: "n. 下午", example: "Let's meet this afternoon." },
    { word: "again", phonetic: "/əˈɡen/", meaning: "adv. 再次", example: "Please read the sentence again." },
    { word: "against", phonetic: "/əˈɡenst/", meaning: "prep. 反對 / 緊靠着", example: "Our team will play against theirs." },
    { word: "age", phonetic: "/eɪdʒ/", meaning: "n. 年齡", example: "She left home at the age of eighteen." },
    { word: "ago", phonetic: "/əˈɡəʊ/", meaning: "adv. 前", example: "I finished my homework two hours ago." },
    { word: "agree", phonetic: "/əˈɡriː/", meaning: "v. 同意", example: "I agree with your plan completely." },
    { word: "ahead", phonetic: "/əˈhed/", meaning: "adv. 在前面", example: "Go straight ahead and turn left." },
    { word: "aim", phonetic: "/eɪm/", meaning: "n. 目標", example: "His main aim is to win the game." },
    { word: "air", phonetic: "/eər/", meaning: "n. 空氣", example: "We need fresh air in the room." },
    { word: "airplane", phonetic: "/ˈeə.pleɪn/", meaning: "n. 飛機", example: "The airplane landed safely at the airport." },
    { word: "airport", phonetic: "/ˈeə.pɔːt/", meaning: "n. 機場", example: "We arrived at the airport early." },
    { word: "album", phonetic: "/ˈæl.bəm/", meaning: "n. 相簿 / 專輯", example: "She showed me her family album." },
    { word: "alike", phonetic: "/əˈlaɪk/", meaning: "adj. 相似的", example: "The twin brothers look very much alike." },
    { word: "alive", phonetic: "/əˈlaɪv/", meaning: "adj. 活着的", example: "Keep your dream alive." },
    { word: "all", phonetic: "/ɔːl/", meaning: "pron. 全部", example: "All of us love English." },
    { word: "allow", phonetic: "/əˈlaʊ/", meaning: "v. 允許", example: "Parents shouldn't allow kids to stay up late." },
    { word: "almost", phonetic: "/ˈɔːl.məʊst/", meaning: "adv. 幾乎", example: "I am almost done with my work." },
    { word: "alone", phonetic: "/əˈləʊn/", meaning: "adv. 單獨地", example: "He prefers to study alone in his room." },
    { word: "along", phonetic: "/əˈlɒŋ/", meaning: "prep. 沿著", example: "They walked along the river bank." },
    { word: "already", phonetic: "/ɔːlˈred.i/", meaning: "adv. 已經", example: "I have already finished my dinner." },
    { word: "also", phonetic: "/ˈɔːlsəʊ/", meaning: "adv. 也", example: "She speaks English and also learns French." },
    { word: "although", phonetic: "/ɔːlˈðəʊ/", meaning: "conj. 雖然", example: "Although it rained, we enjoyed the trip." },
    { word: "always", phonetic: "/ˈɔːl.weɪz/", meaning: "adv. 總是", example: "She always drinks milk in the morning." },
    { word: "america", phonetic: "/əˈmer.ɪ.kə/", meaning: "n. 美國", example: "They are planning a trip to America." },
    { word: "american", phonetic: "/əˈmer.ɪ.kən/", meaning: "adj. 美國的", example: "I enjoy watching American movies." },
    { word: "among", phonetic: "/əˈmʌŋ/", meaning: "prep. 在…之中", example: "She is popular among her classmates." },
    { word: "amount", phonetic: "/əˈmaʊnt/", meaning: "n. 數量", example: "A large amount of water was wasted." },
    { word: "ancient", phonetic: "/ˈeɪn.ʃənt/", meaning: "adj. 古老的", example: "They visited an ancient castle in Rome." },
    { word: "and", phonetic: "/ænd/", meaning: "conj. 和", example: "I like coffee and tea." },
    { word: "anger", phonetic: "/ˈæŋ.ɡər/", meaning: "n. 憤怒", example: "He spoke with anger in his voice." },
    { word: "angry", phonetic: "/ˈæŋ.ɡri/", meaning: "adj. 生氣的", example: "Don't get angry over small things." },
    { word: "animal", phonetic: "/ˈæn.ɪ.məl/", meaning: "n. 動物", example: "Dogs are very friendly animals." },
    { word: "another", phonetic: "/əˈnʌð.ər/", meaning: "det. 另一個", example: "Would you like another cup of tea?" },
    { word: "answer", phonetic: "/ˈɑːn.sər/", meaning: "v. 回答", example: "Please answer my question." },
    { word: "ant", phonetic: "/ænt/", meaning: "n. 螞蟻", example: "Look at the ant carrying food." },
    { word: "any", phonetic: "/ˈen.i/", meaning: "det. 任何", example: "Do you have any questions?" },
    { word: "anybody", phonetic: "/ˈen.iˌbɒd.i/", meaning: "pron. 任何人", example: "Does anybody know the answer?" },
    { word: "anymore", phonetic: "/ˌen.iˈmɔːr/", meaning: "adv. 再也（不）", example: "He doesn't live here anymore." },
    { word: "anyone", phonetic: "/ˈen.i.wʌn/", meaning: "pron. 任何人", example: "Is anyone in the classroom?" },
    { word: "anything", phonetic: "/ˈen.i.θɪŋ/", meaning: "pron. 任何事物", example: "I didn't see anything unusual." },
    { word: "anyway", phonetic: "/ˈen.i.weɪ/", meaning: "adv. 無論如何", example: "Thanks for your help anyway." },
    { word: "anywhere", phonetic: "/ˈen.i.weər/", meaning: "adv. 任何地方", example: "You can sit anywhere you like." },
    { word: "apartment", phonetic: "/əˈpɑːt.mənt/", meaning: "n. 公寓", example: "They live in a small apartment." },
    { word: "appear", phonetic: "/əˈpɪər/", meaning: "v. 出現", example: "A rainbow appeared after the rain." },
    { word: "apple", phonetic: "/ˈæp.əl/", meaning: "n. 蘋果", example: "An apple a day keeps the doctor away." },
    { word: "apply", phonetic: "/əˈplaɪ/", meaning: "v. 申請", example: "He plans to apply for college next year." },
    { word: "appreciate", phonetic: "/əˈpriː.ʃi.eɪt/", meaning: "v. 感激", example: "I appreciate your help very much." },
    { word: "area", phonetic: "/ˈeə.ri.ə/", meaning: "n. 區域", example: "Children like to play in this area." },
    { word: "arm", phonetic: "/ɑːm/", meaning: "n. 手臂", example: "He broke his arm during the game." },
    { word: "army", phonetic: "/ˈɑːmi/", meaning: "n. 軍隊", example: "He joined the army after high school." },
    { word: "around", phonetic: "/əˈraʊnd/", meaning: "prep. 大約 / 在…周圍", example: "The Earth moves around the Sun." },
    { word: "arrange", phonetic: "/əˈreɪndʒ/", meaning: "v. 安排", example: "Let's arrange a meeting for tomorrow." },
    { word: "arrive", phonetic: "/əˈraɪv/", meaning: "v. 到達", example: "What time will the train arrive?" },
    { word: "art", phonetic: "/ɑːt/", meaning: "n. 藝術", example: "She is very good at art and music." },
    { word: "article", phonetic: "/ˈɑː.tɪ.kəl/", meaning: "n. 文章", example: "I read an interesting article today." },
    { word: "artist", phonetic: "/ˈɑː.tɪst/", meaning: "n. 藝術家", example: "The artist painted a beautiful picture." },
    { word: "as", phonetic: "/æz/", meaning: "prep. 作為 / 當…時", example: "As a student, you should study hard." },
    { word: "ask", phonetic: "/ɑːsk/", meaning: "v. 詢問", example: "Feel free to ask if you have questions." },
    { word: "asleep", phonetic: "/əˈsliːp/", meaning: "adj. 睡著的", example: "The baby fell asleep quickly." },
    { word: "assist", phonetic: "/əˈsɪst/", meaning: "v. 協助", example: "She came to assist us with the project." },
    { word: "assistant", phonetic: "/əˈsɪs.tənt/", meaning: "n. 助手", example: "The doctor asked his assistant for help." },
    { word: "at", phonetic: "/æt/", meaning: "prep. 在", example: "Let's meet at the station." },
    { word: "attack", phonetic: "/əˈtæk/", meaning: "v. 攻擊", example: "Tigers rarely attack humans." },
    { word: "attend", phonetic: "/əˈtend/", meaning: "v. 出席", example: "All students must attend the meeting." },
    { word: "attention", phonetic: "/əˈten.ʃən/", meaning: "n. 注意力", example: "Pay attention to what the teacher says." },
    { word: "attract", phonetic: "/əˈtrækt/", meaning: "v. 吸引", example: "The bright flowers attract butterflies." },
    { word: "audience", phonetic: "/ˈɔː.di.əns/", meaning: "n. 觀眾", example: "The audience applauded after the show." },
    { word: "aunt", phonetic: "/ɑːnt/", meaning: "n. 姑姑 / 阿姨", example: "My aunt visits us every weekend." },
    { word: "australia", phonetic: "/ɒsˈtreɪ.li.ə/", meaning: "n. 澳洲", example: "Kangaroos are native to Australia." },
    { word: "australian", phonetic: "/ɒsˈtreɪ.li.ən/", meaning: "adj. 澳洲的", example: "We met an Australian family on vacation." },
    { word: "autumn", phonetic: "/ˈɔː.təm/", meaning: "n. 秋天", example: "Leaves turn yellow in autumn." },
    { word: "available", phonetic: "/əˈveɪ.lə.bəl/", meaning: "adj. 可得到的", example: "Is this seat available?" },
    { word: "avoid", phonetic: "/əˈvɔɪd/", meaning: "v. 避免", example: "We should avoid making the same mistake." },
    { word: "awake", phonetic: "/əˈweɪk/", meaning: "adj. 清醒的", example: "I was still awake at midnight." },
    { word: "award", phonetic: "/əˈwɔːd/", meaning: "n. 獎項", example: "She won an award for her piano performance." },
    { word: "away", phonetic: "/əˈweɪ/", meaning: "adv. 離開", example: "Put your toys away now." },
    { word: "awesome", phonetic: "/ˈɔː.səm/", meaning: "adj. 很棒的", example: "The concert was absolutely awesome." },
    { word: "awful", phonetic: "/ˈɔː.fəl/", meaning: "adj. 糟糕的", example: "The weather today is awful." }
];
